### ISSUE TITLE
Figure out system for accurate colonist state changes

### ISSUE THREAD

**Issue by znichola** [zinovic/ColonialCharter#1]
Currently colonists have a chance of death/injury then the remainder for normal, these don't always fire at the same time, so you can have a colonist disappear. 

```
results =
  {
    {
      name = "injured-colonist",
      probability = 0.08,
      amount = 1
    },
    {
      name = "tired-colonist",
      probability = 0.92,
      amount = 1
    },
    {
      name = "tired-colonist",
      amount = 2
    },
    {
      name = "space-science-pack",
      amount = 5
    }
  },
```

**Comment by Tarrke** [comment]
Just to find the revelant place: recipes.lua lines 57 to 74, lines 192 to 212, lines 257 to 281.

If I get it right, the problem is that with this, either 0, 1 or 2 colonists may be created as result of this recipe.

To reproduce or test:
To Be Done

**Comment by znichola** [comment]
So their should always be two colonist, and 98% of the time a third, with 8% of the time an injured. Input into the recipe is three colonist, ideally only three get returned, as injured or normal. As it is sometimes you get 3 and 1 injured others times just 2 and any combinatino in-between.

**Comment by Tarrke** [comment]
Out of the box I'll check the implementation of the Uranium enrichisment cycle, to have something to get started with.
I tried a few search in the mod forum but was not lucky. I'll search more after I got the mod running (that's good) and the Colonist are doing things. More on that later.

**Comment by Tarrke** [comment]
I've played a bit with the Uranium enrichisment cycle, in the end this is exactly as stated here: sometime the cycle does not provides anything from uranium.
I'm not sure this can be fixed. Your best hope is to ask the question in the Factorio Mod Forum. Maybe Bob or Angel have a solution to that, but really not sure.

**Comment by znichola** [comment]
It seems like it would be an involved solution, will come back to it when more the mod is more complete as it's not a huge issue. We can also mitigate it by increasing the number of colonist that get shipped with each rocket so being one down for a work/rest cycle is not so noticeable.
