### ISSUE TITLE
Launching game after running deployment script

### ISSUE THREAD

**Issue by znichola** [zinovic/ColonialCharter#3]
@Tarrke is it possible to add in an option to launch the game after running the deployment script, as I was messing with the graphics it takes a lot of restarts to get the shadows lined up, it would make it much easier if the game auto launched after deploying.

**Comment by Tarrke** [comment]
Yes this is possible. Let me toy around with this for the day. I'll upload a new version of the scritp.

**Comment by Tarrke** [comment]
I change some things to adress the no steam factorio installation. You'll have to set a variable in the script so this will work. I'll test this tonight at home before making a new PR.

**Comment by znichola** [comment]
Yeah that's awesome, I think I saw a setting in the githud desktop where files could be ignored when merging so my setting won't affect the repo.

**Comment by Tarrke** [comment]
This is easily done via the .gitignore file. You'll find the [documentation here](https://git-scm.com/docs/gitignore).

I'm thinking about a configuration file, but did not had the time to test this this morning before my meetings. Maybe I'll go that way, the config file should be in the gitignore file and the script then could remains in the repo unchanged.

I'll spend the evening on this and the gui I think.
